from __future__ import annotations

ADMISSION_TOKEN_ENV_VAR = "ORCA_AUTO_ORCA_ADMISSION_TOKEN"
ADMISSION_APP_NAME_ENV_VAR = "ORCA_AUTO_ORCA_ADMISSION_APP_NAME"
ADMISSION_TASK_ID_ENV_VAR = "ORCA_AUTO_ORCA_ADMISSION_TASK_ID"

__all__ = [
    "ADMISSION_APP_NAME_ENV_VAR",
    "ADMISSION_TASK_ID_ENV_VAR",
    "ADMISSION_TOKEN_ENV_VAR",
]
