from __future__ import annotations

STATUS_CANCEL_REQUESTED = "cancel_requested"
STATUS_CANCEL_FAILED = "cancel_failed"
STATUS_CANCELLED = "cancelled"
STATUS_COMPLETED = "completed"
STATUS_CREATED = "created"
STATUS_FAILED = "failed"
STATUS_PENDING = "pending"
STATUS_PLANNED = "planned"
STATUS_QUEUED = "queued"
STATUS_RETRYING = "retrying"
STATUS_RUNNING = "running"
STATUS_SUBMISSION_FAILED = "submission_failed"
STATUS_SUBMITTED = "submitted"
STATUS_UNKNOWN = "unknown"

TERMINAL_STATUSES = frozenset({STATUS_COMPLETED, STATUS_FAILED, STATUS_CANCELLED})
FAILED_STATUSES = frozenset({STATUS_FAILED, STATUS_CANCEL_FAILED, STATUS_SUBMISSION_FAILED})
WORKFLOW_ACTIVE_STATUSES = frozenset(
    {
        STATUS_CREATED,
        STATUS_PLANNED,
        STATUS_PENDING,
        STATUS_QUEUED,
        STATUS_SUBMITTED,
        STATUS_RUNNING,
        STATUS_RETRYING,
        STATUS_CANCEL_REQUESTED,
    }
)
WORKFLOW_FAILED_STATUSES = FAILED_STATUSES
WORKFLOW_ATTENTION_STATUSES = WORKFLOW_FAILED_STATUSES
WORKFLOW_TERMINAL_STATUSES = frozenset(
    {STATUS_COMPLETED, STATUS_CANCELLED, *WORKFLOW_FAILED_STATUSES}
)
WORKFLOW_STATUS_ORDER = (
    STATUS_RUNNING,
    STATUS_QUEUED,
    STATUS_SUBMITTED,
    STATUS_PLANNED,
    STATUS_RETRYING,
    STATUS_CANCEL_REQUESTED,
    STATUS_FAILED,
    STATUS_CANCEL_FAILED,
    STATUS_SUBMISSION_FAILED,
)
QUEUE_ACTIVE_STATUSES = frozenset(
    {
        STATUS_PLANNED,
        STATUS_PENDING,
        STATUS_QUEUED,
        STATUS_SUBMITTED,
        STATUS_RUNNING,
        STATUS_RETRYING,
        STATUS_CANCEL_REQUESTED,
    }
)
STAGE_TERMINAL_STATUSES = WORKFLOW_TERMINAL_STATUSES

__all__ = [
    "FAILED_STATUSES",
    "QUEUE_ACTIVE_STATUSES",
    "STAGE_TERMINAL_STATUSES",
    "STATUS_CANCEL_FAILED",
    "STATUS_CANCEL_REQUESTED",
    "STATUS_CANCELLED",
    "STATUS_COMPLETED",
    "STATUS_CREATED",
    "STATUS_FAILED",
    "STATUS_PENDING",
    "STATUS_PLANNED",
    "STATUS_QUEUED",
    "STATUS_RETRYING",
    "STATUS_RUNNING",
    "STATUS_SUBMISSION_FAILED",
    "STATUS_SUBMITTED",
    "STATUS_UNKNOWN",
    "TERMINAL_STATUSES",
    "WORKFLOW_ACTIVE_STATUSES",
    "WORKFLOW_ATTENTION_STATUSES",
    "WORKFLOW_FAILED_STATUSES",
    "WORKFLOW_STATUS_ORDER",
    "WORKFLOW_TERMINAL_STATUSES",
]
