from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

import yaml

from ..config import _default_organized_root, load_config
from ..pathing import is_rejected_windows_path, is_subpath
from ._helpers import default_config_path

logger = logging.getLogger(__name__)


def _prompt_text(label: str, default: str | None = None) -> str:
    suffix = f" [{default}]" if default is not None and default != "" else ""
    value = input(f"{label}{suffix}: ").strip()
    if value:
        return value
    return default or ""


def _prompt_yes_no(label: str, *, default: bool) -> bool:
    hint = "Y/n" if default else "y/N"
    while True:
        value = input(f"{label} [{hint}]: ").strip().lower()
        if not value:
            return default
        if value in {"y", "yes"}:
            return True
        if value in {"n", "no"}:
            return False
        print("Please answer y or n.")


def _normalize_linux_path(raw: str, *, label: str) -> Path | None:
    if not raw.strip():
        print(f"{label} is required.")
        return None
    if is_rejected_windows_path(raw):
        print(f"{label} must be a Linux path, not a Windows path: {raw}")
        return None

    path = Path(raw).expanduser()
    if not path.is_absolute():
        print(f"{label} must be an absolute Linux path.")
        return None
    return path.resolve(strict=False)


def _prompt_orca_executable() -> str:
    while True:
        raw = _prompt_text("ORCA executable path")
        path = _normalize_linux_path(raw, label="orca_executable")
        if path is None:
            continue
        if str(path).lower().endswith(".exe"):
            print("orca_executable must point to a Linux ORCA binary, not a Windows .exe.")
            continue
        if not path.exists():
            print(f"File not found: {path}")
            continue
        if not path.is_file():
            print(f"Path is not a file: {path}")
            continue
        return str(path)


def _prompt_directory_path(label: str, *, default: str | None = None) -> Path:
    while True:
        raw = _prompt_text(label, default)
        path = _normalize_linux_path(raw, label=label)
        if path is None:
            continue
        if path.exists() and not path.is_dir():
            print(f"{label} is not a directory: {path}")
            continue
        return path


def _ensure_directory(path: Path, *, label: str) -> bool:
    if path.exists():
        return True
    if not _prompt_yes_no(f"{label} does not exist. Create it now?", default=True):
        print(f"{label} was not created.")
        return False
    path.mkdir(parents=True, exist_ok=True)
    return True


def _prompt_organized_root(allowed_root: Path) -> str:
    default_path = _default_organized_root(str(allowed_root))
    while True:
        path = _prompt_directory_path("organized_root directory", default=default_path)
        if is_subpath(path, allowed_root) or is_subpath(allowed_root, path):
            print(
                "organized_root and allowed_root must not contain each other. "
                f"allowed_root={allowed_root}, organized_root={path}"
            )
            continue
        if not _ensure_directory(path, label="organized_root"):
            continue
        return str(path)


def _prompt_default_max_retries() -> int:
    while True:
        raw = _prompt_text("default_max_retries", "2")
        try:
            value = int(raw)
        except ValueError:
            print("default_max_retries must be an integer >= 0.")
            continue
        if value < 0:
            print("default_max_retries must be an integer >= 0.")
            continue
        return value


def _prompt_telegram_config() -> dict[str, str]:
    if not _prompt_yes_no("Configure Telegram notifications now?", default=False):
        return {"bot_token": "", "chat_id": ""}

    while True:
        bot_token = _prompt_text("Telegram bot token")
        chat_id = _prompt_text("Telegram chat id")
        if bot_token and chat_id:
            return {"bot_token": bot_token, "chat_id": chat_id}
        print("Both Telegram bot token and chat id are required, or choose not to configure Telegram.")


def _write_config(config_path: Path, payload: dict[str, object]) -> None:
    config_path.parent.mkdir(parents=True, exist_ok=True)
    rendered = yaml.safe_dump(payload, sort_keys=False, allow_unicode=True)
    config_path.write_text(f"# Generated by orca_auto init\n{rendered}", encoding="utf-8")


def cmd_init(args: Any) -> int:
    force = bool(getattr(args, "force", False))
    config_path = Path(default_config_path()).expanduser().resolve()

    if config_path.exists() and not force:
        overwrite = _prompt_yes_no(
            f"Config already exists at {config_path}. Overwrite it?",
            default=False,
        )
        if not overwrite:
            print("Cancelled.")
            return 0

    print(f"Creating config at: {config_path}")

    try:
        orca_executable = _prompt_orca_executable()
        allowed_root = _prompt_directory_path("allowed_root directory")
        while not _ensure_directory(allowed_root, label="allowed_root"):
            allowed_root = _prompt_directory_path("allowed_root directory")
        organized_root = _prompt_organized_root(allowed_root)
        default_max_retries = _prompt_default_max_retries()
        telegram = _prompt_telegram_config()
    except (EOFError, KeyboardInterrupt):
        print("\nCancelled.")
        return 1

    payload: dict[str, object] = {
        "runtime": {
            "allowed_root": str(allowed_root),
            "organized_root": organized_root,
            "default_max_retries": default_max_retries,
        },
        "paths": {
            "orca_executable": orca_executable,
        },
        "telegram": telegram,
    }

    try:
        _write_config(config_path, payload)
        load_config(str(config_path))
    except Exception as exc:
        logger.exception("Failed to generate config: %s", exc)
        print(f"Failed to generate config: {exc}")
        return 1

    print("Config created successfully.")
    print(f"  config: {config_path}")
    print(f"  allowed_root: {allowed_root}")
    print(f"  organized_root: {organized_root}")
    print(f"  orca_executable: {orca_executable}")
    return 0
